name: Test Security Tools container build
on:
  push:
    branches:
      - main
      - develop
    paths:
      - Dockerfile
  pull_request:
    branches:
      - main
      - develop
    paths:
      - Dockerfile

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container using Make
        run: make build
        env:
          DOCKER_BUILDKIT: 1